### ISSUE TITLE
Running in to exception working with Pipeline API

### ISSUE THREAD

**Issue by sboorugu** [hazelcast/hazelcast-jet-code-samples#164]
Team,

I am using Pipeline api to read from a list , transform them to uppercase and then write to an a list using Jet.

When i am running this on server experiencing below exception:
```
Exception in thread "main" com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.core.DAG'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:157)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:133)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:118)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toData(AbstractSerializationService.java:106)
	at com.hazelcast.jet.impl.AbstractJobProxy.doSubmitJob(AbstractJobProxy.java:205)
	at com.hazelcast.jet.impl.AbstractJobProxy.<init>(AbstractJobProxy.java:80)
	at com.hazelcast.jet.impl.JobProxy.<init>(JobProxy.java:53)
	at com.hazelcast.jet.impl.JetInstanceImpl.newJob(JetInstanceImpl.java:61)
	at com.hazelcast.jet.JetInstance.newJob(JetInstance.java:72)
	at com.hazelcast.jet.JetInstance.newJob(JetInstance.java:92)
	at com.walmart.jet.hadoop.PipelineSample.main(PipelineSample.java:45)
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.core.Vertex'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:254)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:375)
	at com.hazelcast.jet.core.DAG.writeData(DAG.java:440)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toBytes(AbstractSerializationService.java:154)
	... 10 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: Failed to serialize 'com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject'
	at com.hazelcast.internal.serialization.impl.SerializationUtil.handleSerializeException(SerializationUtil.java:75)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:254)
	at com.hazelcast.internal.serialization.impl.ByteArrayObjectDataOutput.writeObject(ByteArrayObjectDataOutput.java:375)
	at com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject.write(CustomClassLoadedObject.java:50)
	at com.hazelcast.jet.core.Vertex.writeData(Vertex.java:187)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:244)
	at com.hazelcast.internal.serialization.impl.DataSerializableSerializer.write(DataSerializableSerializer.java:51)
	at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.write(StreamSerializerAdapter.java:43)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:252)
	... 16 more
Caused by: com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable serializer for class com.hazelcast.jet.impl.execution.init.CustomClassLoadedObject
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.serializerFor(AbstractSerializationService.java:487)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.writeObject(AbstractSerializationService.java:250)
```

--- 

Below is the code:

		 JetConfig cfg = new JetConfig();
	        cfg.setInstanceConfig(new InstanceConfig().setCooperativeThreadCount(
	                Math.max(1, getRuntime().availableProcessors() / 2)));

	        JetInstance jet = Jet.newJetInstance(cfg);
	       
	        Jet.newJetInstance(cfg);
	        IListJet<String> input = jet.<String>getList("input");
            input.addAll(new ArrayList<>( Arrays.asList("test", "test1", "test2")));
	        
	        
		Pipeline p = Pipeline.create();
		p.drawFrom(Sources.<String>list("input"))
		 .map(String::toUpperCase)
		 .drainTo(Sinks.list("result"));
		
		try {
            System.out.print("\nCounting words from "+"\n");
            long start = nanoTime();
            jet.newJob(p).join();
            
            System.out.println("Done in " + NANOSECONDS.toMillis(nanoTime() - start) + " milliseconds.");
            System.out.println("Output written to " + jet.getList("result").get(1));
        } finally {
            Jet.shutdownAll();
        }

When i run this in my local it is working, but when i run on server it is throwing above exception.
Please suggest me with a solution.

**Comment by viliam-durina** [comment]
Your code contains a custom lambda (the `String::toUpperCase`). You need to add your class to the job config:
```java
JobConfig jobConfig = new JobConfig();
jobConfig.addClass(PipelineSample.class);
jet.newJob(p, jobConfig).join();
```

When you are submitting to a running cluster, the easiest way is to use the `jet-submit.sh` script, see https://docs.hazelcast.org/docs/jet/0.7.2/manual/#submit-a-job-from-the-command-line.

**Comment by sboorugu** [comment]
Thanks for your suggestion. Let me try out this.
