### ISSUE TITLE
MapSourceAndSinks.mapWithUpdating generates java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap') 	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:250)

### ISSUE THREAD

**Issue by sebvige** [hazelcast/hazelcast-jet-code-samples#202]
Running the mapWithUpdating "as is " generates the exception described above.

Changing  String.valueOf(e.getValue()) to  e.getValue()
and 
 ? oldValue +"--even"
 : oldValue +"--odd"
to 
 ? oldValue
 : oldValue

makes the code running ok but with no parsing and suffixing

**Comment by viliam-durina** [comment]
Please share the entire code of the pipeline. Is the type parameter of the source (at `drawFrom`) correct, does it correspond to the actual type of data in the source?

**Comment by sebvige** [comment]
Here is the code as it is today in the repo : 
 private static Pipeline mapWithUpdating(String sourceMapName, String sinkMapName) {
        Pipeline pipeline = Pipeline.create();

        pipeline.drawFrom(Sources.<Integer, Integer>map(sourceMapName))
                .map(e -> entry(e.getKey(), String.valueOf(e.getValue())))
                .drainTo(
                        Sinks.mapWithUpdating(
                                sinkMapName,
                                (oldValue, item) ->
                                        item.getKey() % 2 == 0
                                                ? oldValue + "-even"
                                                : oldValue + "-odd"
                        )
                );

        return pipeline;
    }

**Comment by viliam-durina** [comment]
I suspect that the sink map already contains items with `Integer` type. The sink map has to be of type `<Integer, String>` and all items in it have to match the signature. If you share the stack trace of the exception I could confirm.

**Comment by sebvige** [comment]
Here is the stack trace : 
------------Map with Updating ----------------
25:31,500 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] Execution plan for jobId=c303-a152-a420-3f71, jobName='c303-a152-a420-3f71', executionId=90b0-2bd8-0b5d-2b49 initialized
25:31,502 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] Start execution of job 'c303-a152-a420-3f71', execution 90b0-2bd8-0b5d-2b49 from coordinator [192.168.1.17]:5703
25:31,512 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,515 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,518 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,519 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,517 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:177)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:131)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,517 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,524 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,525 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,526 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,529 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
25:31,543 [192.168.1.17]:5704 [jet] [3.1.1-SNAPSHOT] Exception in ProcessorTasklet{mapWithUpdatingSink(mapWithUpdatingSourceSink)#1}
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:43)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Exception in thread "main" java.util.concurrent.CompletionException: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{mapWithUpdatingSink(mapWithUpdatingSourceSink)#0}: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412)
	at java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044)
	at com.hazelcast.jet.Job.join(Job.java:106)
	at MapSourceAndSinks.go(MapSourceAndSinks.java:160)
	at MapSourceAndSinks.main(MapSourceAndSinks.java:128)
Caused by: com.hazelcast.jet.JetException: Exception in ProcessorTasklet{mapWithUpdatingSink(mapWithUpdatingSourceSink)#0}: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.impl.execution.TaskletExecutionService$BlockingWorker.run(TaskletExecutionService.java:250)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
	at ------ submitted from ------.(Unknown Source)
	at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:126)
	at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:251)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64)
	at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80)
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:41)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.process(HazelcastWriters.java:639)
	at com.hazelcast.map.impl.operation.EntryOperator.process(EntryOperator.java:318)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKeyValueInternal(EntryOperator.java:181)
	at com.hazelcast.map.impl.operation.EntryOperator.operateOnKey(EntryOperator.java:166)
	at com.hazelcast.map.impl.operation.MultipleEntryOperation.run(MultipleEntryOperation.java:76)
	at com.hazelcast.spi.Operation.call(Operation.java:170)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:210)
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:199)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:147)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:125)
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.run(OperationThread.java:110)
	... 8 more

**Comment by viliam-durina** [comment]
That's it. Your sink map contained entries with `Integer` value.
```java
        map.put(1, 1);

        Pipeline p = Pipeline.create();
        p.drawFrom(SourceBuilder.batch("src", procCtx -> null)
                .<Entry<Integer, String>>fillBufferFn((ctx, buf) -> {
                    buf.add(entry(1, "foo"));
                    buf.close();
                })
                .build())
         .drainTo(Sinks.mapWithUpdating("sinkMap", (oldValue, item) ->
                 item.getKey() % 2 == 0
                         ? oldValue + "-even"
                         : oldValue + "-odd"));

        inst.newJob(p).join();
```
failed with:
```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.hazelcast.jet.function.BiFunctionEx.apply(BiFunctionEx.java:41)
	at com.hazelcast.jet.impl.connector.HazelcastWriters$ApplyFnEntryProcessor.handle(HazelcastWriters.java:647)
```
